import { authenticationType } from "./authUserReducer";
import { postsDataType } from "./profilePageReducer";

export const getSuperCurrentProfile = (state:any):object|null => state.profilePage.currentProfile;
export const getSuperMyProfile = (state:any):object|null => state.profilePage.myProfile;
export const getCurrentStatus = (state:any):string => state.profilePage.currentStatus;
export const getAuthenticationId = (state:any):number|null => state.authUser.authentication.id;
export const getMessag = (state:any):string => state.dialogsPage.messag;
export const getDialodsPageData = (state:any):Array<object> => state.dialogsPage.data;
export const getAuthenticationUser = (state:any):authenticationType => state.authUser.authentication;
export const getIsAuth = (state:any):boolean => state.authUser.isAuth;
export const getProfile = (state:any):object|null => state.authUser.profile;
export const getPostsData = (state:any):postsDataType => state.profilePage.postsData;
export const getUsers = (state:any):Array<object> => state.usersPage.users;
export const getNumberCurrentPage = (state:any):number => state.usersPage.numberCurrentPage;
export const getCountUsersPage = (state:any):number => state.usersPage.countUsersPage;
export const getTotalCountPage = (state:any):number => state.usersPage.totalCountPage;
export const getLengthCountPage = (state:any):Array<number> => state.usersPage.lengthCountPage;
export const getIsLoader = (state:any):boolean => state.usersPage.isLoader;
export const getIsDisabledFollowButton = (state:any):Array<number> => state.usersPage.isDisabledFollowButton;
export const getTopFriends = (state:any):Array<Object> => state.app.topFriends;
export const getIsMyPages = (state:any):boolean => state.profilePage.isMyPages;
export const getCaptchaUrl = (state:any):null|string => state.authUser.captchaUrl;
export const getError = (state:any):object|null => state.app.error;
export const getListMusics = (state:any):Array<object> => state.musicPage.listMusics;
export const getCurrentMove = (state:any):string => state.games.crossOrZero.currentMove;
export const getCountMove = (state:any):number => state.games.crossOrZero.countMove;
export const getCombinationRed = (state:any):any => state.games.crossOrZero.red.combinationRed;
export const getCombinationBlue = (state:any):any => state.games.crossOrZero.blue.combinationBlue;
export const getCurrentVictoriCrossOrZero = (state:any):string => state.games.crossOrZero.currentVictori;
export const getVictoriRed = (state:any):number => state.games.crossOrZero.red.victoriRed;
export const getVictoriBlue = (state:any):number => state.games.crossOrZero.blue.victoriBlue;
export const getNameBlue = (state:any):string => state.games.crossOrZero.blue.nameBlue;
export const getNameRed = (state:any):string => state.games.crossOrZero.red.nameRed;