const SET_INITIALLIZED = "SET_INITIALLIZED";
const SET_AUTH_USER = "SET_AUTH_USER";
const TOGGLE_BAR = "TOGGLE_BAR";
const SET_PROFILE = 'SET_PROFILE';
const ADD_MESSAG = "ADD_MESSAG";
const ADD_POST = 'ADD_POST';
const SET_CURRENT_PROFILE = 'SET_CURRENT_PROFILE';
const SET_CURRENT_STATUS = 'SET_CURRENT_STATUS';
const DELETE_POST = 'DELETE_POST';
const FOLLOW = 'FOLLOW';
const UNFOLLOW = 'UNFOLLOW';
const SET_USERS = 'SET_USERS';
const SET_MY_PROFILE = 'SET_MY_PROFILE';
const SET_TOTAL_COUNT_PAGE = 'SET_TOTAL_COUNT_PAGE';
const SET_LENGTH_COUNT_PAGE = 'SET_LENGTH_COUNT_PAGE';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
const TOGGLE_ISLOADER = 'TOGGLE_ISLOADER';
const TOGGLE_DISABLED_FOLLOW = 'TOGGLE_DISABLED_FOLLOW';
const SET_TOP_FRIENDS = 'SET_TOP_FRIENDS';
const SAVE_PHOTO = 'SAVE_PHOTO';
const IS_MY_PAGES = 'IS_MY_PAGES';
const UPDATE_MY_INFO = 'UPDATE_MY_INFO';
const GET_CAPTCHA = 'GET_CAPTCHA';
const SET_ERROR = 'SET_ERROR';
const SET_CURRENT_MOVE = 'SET_CURRENT_MOVE';
const SET_COMBINATION_RED = 'SET_COMBINATION_RED';
const SET_COMBINATION_BLUE = 'SET_COMBINATION_BLUE';
const CROSS_OR_ZERO_EXAMINATION = 'CROSS_OR_ZERO_EXAMINATION';
const SET_CURRENT_VICTORI = 'SET_CURRENT_VICTORI';
const SET_NEW_GAME_COZ = 'SET_NEW_GAME_COZ';
const SET_NAME_BLUE = 'SET_NAME_BLUE';
const SET_NAME_RED = 'SET_NAME_RED';
const SET_FRIEND = 'SET_FRIEND';
const SET_SEARCH = 'SET_SEARCH';

export {
  SET_INITIALLIZED,
  SET_NAME_RED,
  SET_SEARCH,
  SET_NAME_BLUE,
  SET_CURRENT_VICTORI,
  SET_FRIEND,
  SET_NEW_GAME_COZ,
  UPDATE_MY_INFO,
  CROSS_OR_ZERO_EXAMINATION,
  SET_COMBINATION_RED,
  SET_COMBINATION_BLUE,
  SET_CURRENT_MOVE,
  SET_AUTH_USER,
  TOGGLE_BAR,
  SET_PROFILE,
  SET_MY_PROFILE,
  ADD_MESSAG,
  ADD_POST,
  SET_ERROR,
  GET_CAPTCHA,
  SAVE_PHOTO,
  SET_CURRENT_PROFILE,
  SET_CURRENT_STATUS,
  DELETE_POST,
  FOLLOW,
  UNFOLLOW,
  SET_USERS,
  SET_TOTAL_COUNT_PAGE,
  SET_LENGTH_COUNT_PAGE,
  SET_CURRENT_PAGE,
  TOGGLE_ISLOADER,
  TOGGLE_DISABLED_FOLLOW,
  SET_TOP_FRIENDS,
  IS_MY_PAGES,
}